### ISSUE TITLE
Enhancement: Termageddon blog post

### ISSUE THREAD

**Issue by jferragut** [AlkemyLLC/Alkemy#114]
Termageddon wrote a post for us and we need to upload that to the site.

**Post:** https://docs.google.com/document/d/1EqLcS7XVkMah9Gkj-WjC57rR_UFk6e4UCP05WC80bXU/edit#

**Tasks:**
- [x] Create Author Profile for Donata
- [x] Upload post data for the blog post
- [x] Create a blog image for the post
- [x] Update all external links inside the post to be `rel="noopener noreferrer"`

**Comment by jferragut** [comment]
Waiting on reply from Donata at Termageddon for her profile data.
