### ISSUE TITLE
Feature: Re-design Blog index and Blog single

### ISSUE THREAD

**Issue by jferragut** [AlkemyLLC/Alkemy#127]
The current blog feels a bit cumbersome. I'd like to rework the design and implement something more streamlined.

Design located on figma board.

**Tasks:**
- [x] Design Blog Index
- [x] Design Blog Single template

- [x] Code Blog Index
  - [x] category bar
  - [x] featured blog
  - [x] blog card
  - [x] pagination

- [x] Code Blog Single template
  - [x] category bar
  - [x] hero
  - [x] info bar
  - [x] body
  - [x] react share (https://github.com/nygardk/react-share)
  - [x] author info  
  - [x] disqus comments (https://github.com/tterb/gatsby-plugin-disqus)
  - [x] post navigation (inherit from current template)

**Acceptance:**
- [x] matches design
- [x] works across all devices seemlessly
- [x] able to post comment
- [x] able to view comments
- [x] able to view comment count
- [x] able to share article on social networks
- [x] able to view author information correctly
- [x] able to click to view author profile

**Comment by jferragut** [comment]
linked to #28 and #36
