### ISSUE TITLE
Feature: New about us page design

### ISSUE THREAD

**Issue by jferragut** [AlkemyLLC/Alkemy#128]
The current about alkemy page needs a rework to make it easier to read and more clean/modern.

Design located on the figma board.

**Tasks:**
- [x] Design About Us
- [x] Code About Us

**Acceptance:**
- [x] works seamlessly on all devices
- [x] matches design
