### ISSUE TITLE
Feature: New Customer enquirey form

### ISSUE THREAD

**Issue by jferragut** [AlkemyLLC/Alkemy#129]
Current form is not on all pages for services and cannot be linked to unless the component is included. To simplify this, we should have a separate page for the form and make it linkable in any other page.

**Tasks:**
- [x] List out all needed fields
- [x] Create design for form in figma
- [x] Code form page
- [x] Create validations
- [x] Integrate Netlify form handling
- [x] Create thank you

**Acceptance:**
- [x] Should work seamlessly on all devices
- [x] Should match design
- [x] Validations should work correctly
- [x] form submission should trigger thank you
