### ISSUE TITLE
Enhancement: Remove Extraneous items from pages

### ISSUE THREAD

**Issue by jferragut** [AlkemyLLC/Alkemy#130]
After the Customer Enquiry form is built (#129 ) we will need to update our current pages to remove extraneous items.

**Tasks:**
- [x] Remove Build your dream form component from all pages
- [x] Remove pricing table component on Web Design and eCommerce pages
- [x] build a component (callout) to make project enquiry
- [x] Add component for project enquiry on Web Design
- [x] Add component for project enquiry on Development
- [x] Add component for project enquiry on eCommerce
- [x] Add component for project enquiry on Marketing
- [x] Add component for project enquiry on contact us
- [x] Add component for project enquiry on about us
- [x] Add component for project enquiry on homepage
