### ISSUE TITLE
Feature Request: Update Forms to split off First name from full name and submit as separate field

### ISSUE THREAD

**Issue by jferragut** [AlkemyLLC/Alkemy#64]
**Reason:**
Currently we are only submitting the Full Name as one field on our forms. However, when we use our marketing automation to send emails to the customers we'd like to be personable. 

This requires us to have a First name so that we can send emails with friendly greetings such as "Hi Joe!", etc.

**Idea:**
Since we already have first name, we can use that and create a new variable for `firstName` that splits the `fullName` into an array and takes `array[0]` which should be the first name.

Also, For Netlify, we need to have a hidden field for this "firstName" that automatically has a value of that stateful variable. This will allow Netlify to autodetect the field.

The data in the state is automatically submitted via the `onSubmit` event.

**Tasks:**
- [ ] Create variable in state for `firstName`
- [ ] Split `fullName` and then assign the 0 index to the firstName variable
- [ ] add hidden input that has a value of `this.state.firstName`

**Acceptance Criteria:**
- [ ] Form Submission must work correctly
- [ ] First Name should be visible from netlify form submission area

**Comment by jferragut** [comment]
Don't need this anymore as the forms are being reworked completely. Closing issue.
