### ISSUE TITLE
BUG: OpenGraph Image and description not set to blog image for blog posts

### ISSUE THREAD

**Issue by jferragut** [AlkemyLLC/Alkemy#72]
**Issue:**
When sharing any blog post on facebook, twitter, etc. it defaults to the screenshot of the homepage. This is due to the OG data being hard coded to that image.

**Proposed Resolution:**
What we need to do is create a prop that can be passed to the SEO component from the post, then create a variable that is set to the prop if it was passed, or screenshot of homepage if it wasn't.

There is an example of this with metaDescription on line 63 of the SEO component.

**Tasks:**
- [x] On blog-single, pass prop to the SEO component that contains the blog cover image
- On SEO component
   - [x] receive the prop by declaring the variable and prop-type
   - [x] define a const for the `ogImage` (like on line 63 is doing for the description)
   - [x] replace reference to screenshot in og:image on line 99 from screenshot to the new variable that was defined for `ogImage`
   - [x] add twitter image tag like this 
```jsx
<meta name="twitter:image" content={ogImage}>
```

**Acceptance Criteria:**
- [x] inspect code on any blog post should reveal OG:image set to the blog cover image
- [x] inspect code should also show new twitter image which is set to blog cover
- [x] test on homepage or other page that isn't blog should default to screenshot of home page for image

**Comment by jferragut** [comment]
claimed this one. in progress

**Comment by cxjay26** [comment]
@jferragut there seems to be an issue where the page loads and then goes to a white page.

**Comment by cxjay26** [comment]
<img width="1361" alt="Screen Shot 2019-10-25 at 7 14 57 PM" src="https://user-images.githubusercontent.com/47510888/67609658-d76f7000-f75b-11e9-81b5-1f48179e3ba5.png">

**Comment by jferragut** [comment]
Cleanup, issue was completed.
